commented out unused step in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,7 +32,7 @@ jobs:
       run: |
         docker build -t cssm-scanner .
 
-    - name: Run scanner with --all
-      run: |
-        python -m aws_scanner.main --all || echo "Scanner exited with error (no creds?)"
+#    - name: Run scanner with --all
+#      run: |
+#        python -m aws_scanner.main --all || echo "Scanner exited with error (no creds?)"
 
